Repository qdrant/landing_page, pull requests merged in 2024-03, with the labels that each got.

#681 Blog iframe styles fix
  qdrant-landing/themes/qdrant/static/css/blocks/_qdrant-blog.scss
  qdrant-landing/themes/qdrant/static/css/main.css
Labels: bug

#713 [blog] Qdrant LangChain post
  qdrant-landing/content/blog/using-qdrant-and-langchain.md
  qdrant-landing/static/blog/qdrant-and-langchain/flow-diagram.png
  qdrant-landing/static/blog/qdrant-and-langchain/qdrant-langchain.png
Labels: draft

#636 docs: Added Canopy integration
  qdrant-landing/content/documentation/frameworks/canopy.md
  qdrant-landing/static/documentation/frameworks/canopy-social-preview.png
Labels: do not merge
