Repository qdrant/landing_page, pull requests merged in 2025-04, with the labels that each got.

#1560 docs: DeepEval integration
  qdrant-landing/content/documentation/frameworks/_index.md
  qdrant-landing/content/documentation/frameworks/deepeval.md
Labels: do not merge

#1529 [blog] Qdrant Version 1.14
  qdrant-landing/content/blog/qdrant-1.14.x.md
  qdrant-landing/static/blog/qdrant-1.14.x/community.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/gridstore.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/gridstore.png
  qdrant-landing/static/blog/qdrant-1.14.x/immutable-segments.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/indexation.png
  qdrant-landing/static/blog/qdrant-1.14.x/optimizations.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/parallel-after.png
  qdrant-landing/static/blog/qdrant-1.14.x/parallel-before.png
  qdrant-landing/static/blog/qdrant-1.14.x/reranking.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/segment-optimization.jpg
  qdrant-landing/static/blog/qdrant-1.14.x/social_preview.png
  qdrant-landing/static/blog/qdrant-1.14.x/upgrade.png
  qdrant-landing/static/blog/qdrant-1.14.x/website-search.png
Labels: do not merge

#1594 update rag deepseek tutorial with local inference
  qdrant-landing/content/documentation/rag-deepseek.md
Labels: draft

#1575 new: replace .add and .query with local inference in fastembed semant…
  qdrant-landing/content/documentation/fastembed/fastembed-semantic-search.md
Labels: draft

#1574 new: provide local inference examples in colbert docs
  qdrant-landing/content/documentation/fastembed/fastembed-colbert.md
Labels: draft, do not merge
